cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3: #버킷이름
      bucket: woosik-bucket
    region: #S3 지역
      static: ap-northeast-2
    stack:
      auto: false
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:test