spring:
  #h2:
  #  console:
  #    enabled: true
  #    path: /h2
  datasource:
    url: jdbc:mysql://cs-project-020.czj9etptcqzw.ap-northeast-2.rds.amazonaws.com:3306??characterEncoding=utf8
spring.datasource.username={}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_MYSQL_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/mysql/data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true